version: 2
updates:

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      # Check for updates to GitHub Actions every quarter
      interval: "quarterly"
    labels:
      - "Release Not Needed"
    target-branch: "dev"
    # Group all github-actions updates into a single PR
    groups:
      all-github-actions:
        applies-to: "version-updates"
        patterns:
          - "*"
