name: Change File Included in PR

on:
  pull_request:
    types: [opened, synchronize, reopened, labeled]

permissions:
  contents: read

jobs:
  check-files-in-directory:
    if: ${{ !contains(github.event.pull_request.labels.*.name, 'Release Not Needed') && !contains(github.event.pull_request.labels.*.name, 'Release PR') }}
    name: Change File Included in PR
    runs-on: ubuntu-latest

    steps:
      - name: Checkout PR code
        uses: actions/checkout@v4

      - name: Get List of Changed Files
        id: changed-files
        uses: tj-actions/changed-files@ed68ef82c095e0d48ec87eccea555d944a631a4c #v45

      - name: Check for Change File(s) in .autover/changes/
        run: |
          DIRECTORY=".autover/changes/"
          if echo "${{ steps.changed-files.outputs.all_changed_files }}" | grep -q "$DIRECTORY"; then
            echo "✅ One or more change files in '$DIRECTORY' are included in this PR."
          else
            echo "❌ No change files in '$DIRECTORY' are included in this PR."
            echo "Refer to the 'Adding a change file to your contribution branch' section of https://github.com/aws/aws-lambda-dotnet/blob/master/CONTRIBUTING.md"
            exit 1
          fi
